# This is a sample aws-auth-patch.yml file.
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::034143355118:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-bRUAEBxhGK45
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::034143355118:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-18T17:55:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1262"
  uid: 1d9461bb-53ee-40ee-9a6e-42d85ffd445a
